import type { WorkProject } from '../_types/work';

export const workProjects = [
  {
    slug: 'avsb',
    num: '01',
    title: 'AvsB',
    summary: 'An in-house, CLI-driven A/B testing platform — built from scratch.',
    metaShort: 'CLI-driven experimentation platform built from scratch.',
    tags: ['Next.js', 'TypeScript', 'ClickHouse', 'Product'],
    categories: ['product', 'experimentation'],
    featured: true,
    order: 1,
    year: '2025 – Present',
    type: 'own',
    yearStatus: '2025 · In progress',
    hasCase: true,
    href: '/work/avsb',
  },
  {
    slug: 'kemon-doctor',
    num: '02',
    title: 'Kemon Doctor',
    summary: 'A non-profit platform helping patients in Bangladesh find trustworthy doctors.',
    metaShort: 'Non-profit doctor review platform for Bangladesh.',
    tags: ['Next.js 15', 'PostgreSQL', 'Drizzle', 'Solo'],
    categories: ['product'],
    featured: true,
    order: 2,
    year: '2025 – Present',
    type: 'own',
    yearStatus: '2025 · In progress',
    hasCase: true,
    href: '/work/kemon-doctor',
  },
  {
    slug: 'client',
    num: '03',
    title: 'Client Work',
    summary: '4+ years of A/B tests and conversion experiments for ecommerce and SaaS clients.',
    metaShort: '4+ years of A/B tests for ecommerce & SaaS clients.',
    tags: ['Optimizely', 'Kameleoon', 'Qubit'],
    categories: ['experimentation', 'client'],
    featured: true,
    order: 3,
    year: '2019 – Present',
    type: 'client',
    yearStatus: '2019 – Present',
    hasCase: true,
    href: '/work/client',
  },
  {
    slug: 'flatwhite',
    num: '04',
    title: 'Flatwhite',
    summary: 'Template development for a hotel listing company.',
    metaShort: 'Template development for a hotel listing company.',
    tags: ['HTML', 'SCSS', 'XD to code'],
    categories: ['client'],
    featured: false,
    order: 4,
    year: '2020',
    type: 'client',
    yearStatus: '2020 · Romania',
    hasCase: false,
    href: '/work/client',
  },
  {
    slug: 'crypto-gods',
    num: '05',
    title: 'Crypto Gods',
    summary: 'Landing page for a crypto community, Figma to code.',
    metaShort: 'Landing page for a crypto community, Figma to code.',
    tags: ['HTML', 'SCSS', 'Bootstrap'],
    categories: ['client'],
    featured: false,
    order: 5,
    year: '2020',
    type: 'client',
    yearStatus: '2020',
    hasCase: false,
    href: '/work/client',
  },
  {
    slug: 'pascal',
    num: '06',
    title: 'Pascal',
    summary: 'Website for Pascal Wealth Tech, frontend build.',
    metaShort: 'Website for Pascal Wealth Tech, frontend build.',
    tags: ['React', 'SCSS'],
    categories: ['client'],
    featured: false,
    order: 6,
    year: '2021',
    type: 'client',
    yearStatus: '2021 · Canada',
    hasCase: false,
    href: '/work/client',
  },
] as const satisfies readonly WorkProject[];

export const featuredWorkProjects = workProjects.filter((p) => p.featured);

/** Filter-chip definitions for `/work`. */
export const workFilters = [
  { value: 'all', label: 'All' },
  { value: 'product', label: 'Products' },
  { value: 'experimentation', label: 'Experimentation' },
  { value: 'client', label: 'Client work' },
] as const;

export type WorkFilterValue = (typeof workFilters)[number]['value'];
