import type { WorkProject } from '../_types/work';

export const workProjects = [
  {
    slug: 'avsb',
    num: '01',
    title: 'AvsB',
    summary:
      'A full-stack A/B testing & feature-flag platform — visual editor, statistics engine, edge ingestion, SDKs, built solo.',
    metaShort: 'Full-stack experimentation & feature-flag platform built solo.',
    tags: ['Next.js 16', 'TypeScript', 'ClickHouse', 'Cloudflare Workers', 'Statistics'],
    featured: true,
    order: 1,
    year: '2024 – Present',
    type: 'own',
    yearStatus: '2024 · Pre-launch',
    hasCase: true,
    href: '/work/avsb',
  },
  {
    slug: 'kemon-doctor',
    num: '02',
    title: 'Kemon Doctor',
    summary: 'A non-profit platform helping patients in Bangladesh find trustworthy doctors.',
    metaShort: 'Non-profit doctor review platform for Bangladesh.',
    tags: ['Next.js 16', 'PostgreSQL', 'Drizzle', 'Solo'],
    featured: true,
    order: 2,
    year: '2025 – Present',
    type: 'own',
    yearStatus: '2025 · Building',
    hasCase: true,
    href: '/work/kemon-doctor',
  },
  {
    slug: 'radius',
    num: '03',
    title: 'Radius',
    summary:
      'A central insights platform that makes experiments, UXR observations, and research findable across an organisation — built at Conversion.com.',
    metaShort: 'Central insights & experiments platform built at Conversion.com.',
    tags: ['Next.js', 'TypeScript', 'SCSS', 'GSAP', 'Streaming APIs'],
    featured: true,
    order: 3,
    year: '2025 – Present',
    type: 'agency',
    yearStatus: '2025 · Live',
    hasCase: true,
    href: '/work/radius',
  },
  {
    slug: 'client',
    num: '04',
    title: 'Client Work',
    summary: '4.5+ years of A/B tests and conversion experiments for ecommerce and SaaS clients.',
    metaShort: '4.5+ years of A/B tests for ecommerce & SaaS clients.',
    tags: ['Optimizely', 'Kameleoon', 'Qubit'],
    featured: true,
    order: 4,
    year: '2019 – Present',
    type: 'client',
    yearStatus: '2019 – Present',
    hasCase: true,
    href: '/work/client',
  },
  {
    slug: 'cursimax',
    num: '05',
    title: 'Cursimax',
    summary:
      'Full frontend build for a Spanish-language online course marketplace serving Latin America.',
    metaShort: 'Full frontend for a Spanish-language e-learning marketplace.',
    tags: ['HTML', 'SCSS', 'JavaScript', 'Figma to code'],
    featured: false,
    order: 5,
    year: '2021',
    type: 'client',
    yearStatus: '2021 · Live',
    hasCase: true,
    href: '/work/cursimax',
  },
  {
    slug: 'flatwhite',
    num: '06',
    title: 'Flatwhite',
    summary:
      'Frontend build for a Romanian short-term rentals and property-management company in Oradea.',
    metaShort: 'Frontend build for a Romanian rentals & property-management company.',
    tags: ['HTML', 'SCSS', 'JavaScript', 'XD to code'],
    featured: false,
    order: 6,
    year: '2020',
    type: 'client',
    yearStatus: '2020 · Live',
    hasCase: true,
    href: '/work/flatwhite',
  },
] as const satisfies readonly WorkProject[];

export const featuredWorkProjects = workProjects.filter((p) => p.featured);
